server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_Ventas
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: terrones
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false  application:    name: ms-ventas
        
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

  ##########
  
  cloud:
      config:
          uri:http://localhost:8090
          username:admin
          password:123456
  boot:
    admin:
      cliente:
          url:http://localhost:8090

 